ANCHORS = [
    "Deep-sea pressure & temperature data — the crush zone where physics becomes alien",
    "Seismology & fault-line activity — tremors that happen on no known fault",
    "Fungal network biology — mycelium as distributed cognition beneath soil",
    "Radio telescope anomaly data — signals that have no stellar source",
    "Historical census gaps — entire populations that vanish between two counts",
    "Quantum decoherence measurements — where observation itself changes outcomes",
    "Antarctic ice core samples — what was frozen 800,000 years ago in the gas layers",
    "Infrasound data — frequencies below hearing that produce dread in mammals",
    "Deep time geology — strata that should not exist in the sequence they do",
    "Migratory path anomalies — species that deviate from routes held for millennia",
    "Epidemiological data — disease clusters with no identifiable vector",
    "Atmospheric chemistry — compounds that do not belong in the spectroscopic reading",
    "Submarine canyon sonar — shapes on the ocean floor that do not erode",
    "Dark matter distribution maps — gravity with no visible source",
    "Archaeological site dating contradictions — artifacts older than the civilisation that made them",
    "Bioluminescence depth records — light where no organism should produce it",
    "Sleep study data — EEG patterns that precede death but produce no symptoms",
    "Extinction event timelines — when multiple unrelated species vanish simultaneously",
    "Gravitational lensing anomalies — light bending around objects that aren't there",
    "Soil microbiome data — bacterial colonies that should not survive, yet persist",
    "Permafrost thaw data — what is re-emerging from 10,000-year-old ice",
    "Ocean salinity readings — pockets of water with chemistry unlike surrounding sea",
    "Cave system surveys — passages that lead to spaces larger than the mountain above them",
    "Human chronobiology — circadian disruptions that track with no external stimulus",
    "Tidal data — anomalous surges with no corresponding lunar event",
]

ANGLES = [
    "The data was collected normally. The anomaly was only noticed during archiving, years later.",
    "The measurement is accurate. What it implies cannot be true under current physics.",
    "Multiple independent sources confirmed the same reading. None of them communicated.",
    "The pattern repeats at a frequency that has no natural driver.",
    "The anomaly was documented once. All subsequent attempts to reproduce it find nothing.",
    "The researchers noted it. Then stopped noting it. The records do not explain why.",
    "It is the absence that is wrong — something that should be there and simply is not.",
    "The oldest records show it more clearly. The more modern the data, the weaker the signal.",
    "It only appears in aggregate. At the individual level, everything is normal.",
    "Three people have independently described the same response to the data: they felt watched.",
    "The anomaly resolves if you accept one assumption that no living scientist accepts.",
    "The equipment that recorded it was later decommissioned. The data was never replicated.",
    "Every dataset that contains this anomaly was collected within the same 11-year window.",
    "The anomaly grows at a rate that would be catastrophic — in approximately 900 years.",
    "There is no funding to investigate it further. No one has applied for any.",
]

POVS = [
    "Second person — the reader is inside the event as it happens",
    "First person plural — 'we' — no individual is ever identified",
    "Third person omniscient with deliberate restraint — knows everything, describes almost nothing",
    "False documentary — written as field notes or a log that stops mid-entry",
    "Nested narration — someone recounting what someone else told them, with small discrepancies",
    "No identifiable narrator — pure description of phenomena with no human anchor",
    "First person singular — a scientist writing a report that slowly stops being a report",
    "Second person plural — 'you all' — a collective addressed as a unit",
]

DISTANCES = [
    "Maximum intimacy — the reader is inside a single consciousness",
    "Forensic distance — clinical, observational, no affect",
    "Historical distance — this happened long ago and the narrator survived",
    "Dissolving distance — starts distant, collapses into immediate by the end",
    "Unreliable proximity — narrator is present but their perception is compromised",
    "Absolute removal — no narrator exists; only data and what it implies",
]

PARAS = [
    "Paragraphs compress as the script progresses — longest at top, shortest at end",
    "Alternating rhythm — long paragraph, short paragraph, throughout",
    "Single unbroken block — no paragraph breaks at all",
    "Each paragraph shorter than the previous, without exception",
    "Fragments only — no complete sentences anywhere in the script",
    "Normal prose that suddenly fragments in the final third, with no explanation",
    "Paragraphs expand — shortest at top, longest at end — pressure builds with density",
    "Two sentences per paragraph maximum, throughout — compression without fragments",
]

CONSTRAINTS = [
    "No metaphors — every image must be literal",
    "No questions — nothing in the script is posed as a question",
    "No adjectives in the final 300 words",
    "No character is ever named",
    "No time markers — no 'then', 'after', 'when', 'before'",
    "No dialogue — even quoted speech is paraphrased",
    "Every paragraph must begin with a number or a measurement",
    "The word 'dark' and all synonyms are banned",
    "No verbs of perception — seeing, hearing, feeling, sensing — banned entirely",
    "The script must end on a factual statement, not a dramatic one",
    "No sentence may exceed 15 words",
    "The word 'horror', 'fear', 'terror', 'dread' — none of these may appear",
    "Every claim must be attributable to a real source, cited inline",
    "No paragraph may repeat a noun used in the previous paragraph",
    "The opening word must be a number",
]

DEFAULT_BANS = [
    {"move": "Opening with a rhetorical question to the audience", "type": "opening"},
    {"move": "Starting with a definition or dictionary framing", "type": "opening"},
    {"move": "Second-person address in the opening line", "type": "opening"},
    {"move": "Three-part list structure anywhere in the script", "type": "structure"},
    {"move": "Ending on a question that mirrors the opening", "type": "ending"},
    {"move": "Zooming out to cosmic scale in the final paragraph", "type": "ending"},
    {"move": "Unnamed protagonist who 'notices something is wrong'", "type": "pov"},
    {"move": "Fake academic citation as an authority device", "type": "device"},
    {"move": "The phrase 'what if I told you'", "type": "device"},
    {"move": "Countdown or enumerated revelation structure", "type": "structure"},
    {"move": "Scientist discovers anomaly, ignores it, later regrets it", "type": "structure"},
    {"move": "Ending with 'we may never know the truth'", "type": "ending"},
    {"move": "Opening with atmospheric weather or environmental description", "type": "opening"},
    {"move": "A character reading a document that contains the horror", "type": "device"},
    {"move": "Flashback structure — present tense interrupted by past", "type": "structure"},
]
